// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"beacon/beacond/models"
)

// GetBeaconReader is a Reader for the GetBeacon structure.
type GetBeaconReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBeaconReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBeaconOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /beacon] GetBeacon", response, response.Code())
	}
}

// NewGetBeaconOK creates a GetBeaconOK with default headers values
func NewGetBeaconOK() *GetBeaconOK {
	return &GetBeaconOK{}
}

/*
GetBeaconOK describes a response with status code 200, with default header values.

OK
*/
type GetBeaconOK struct {
	Payload *models.ServerBeaconDescribeResponse
}

// IsSuccess returns true when this get beacon o k response has a 2xx status code
func (o *GetBeaconOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get beacon o k response has a 3xx status code
func (o *GetBeaconOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get beacon o k response has a 4xx status code
func (o *GetBeaconOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get beacon o k response has a 5xx status code
func (o *GetBeaconOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get beacon o k response a status code equal to that given
func (o *GetBeaconOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get beacon o k response
func (o *GetBeaconOK) Code() int {
	return 200
}

func (o *GetBeaconOK) Error() string {
	return fmt.Sprintf("[GET /beacon][%d] getBeaconOK  %+v", 200, o.Payload)
}

func (o *GetBeaconOK) String() string {
	return fmt.Sprintf("[GET /beacon][%d] getBeaconOK  %+v", 200, o.Payload)
}

func (o *GetBeaconOK) GetPayload() *models.ServerBeaconDescribeResponse {
	return o.Payload
}

func (o *GetBeaconOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerBeaconDescribeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
