// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBeaconParams creates a new GetBeaconParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBeaconParams() *GetBeaconParams {
	return &GetBeaconParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBeaconParamsWithTimeout creates a new GetBeaconParams object
// with the ability to set a timeout on a request.
func NewGetBeaconParamsWithTimeout(timeout time.Duration) *GetBeaconParams {
	return &GetBeaconParams{
		timeout: timeout,
	}
}

// NewGetBeaconParamsWithContext creates a new GetBeaconParams object
// with the ability to set a context for a request.
func NewGetBeaconParamsWithContext(ctx context.Context) *GetBeaconParams {
	return &GetBeaconParams{
		Context: ctx,
	}
}

// NewGetBeaconParamsWithHTTPClient creates a new GetBeaconParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBeaconParamsWithHTTPClient(client *http.Client) *GetBeaconParams {
	return &GetBeaconParams{
		HTTPClient: client,
	}
}

/*
GetBeaconParams contains all the parameters to send to the API endpoint

	for the get beacon operation.

	Typically these are written to a http.Request.
*/
type GetBeaconParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get beacon params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBeaconParams) WithDefaults() *GetBeaconParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get beacon params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBeaconParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get beacon params
func (o *GetBeaconParams) WithTimeout(timeout time.Duration) *GetBeaconParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get beacon params
func (o *GetBeaconParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get beacon params
func (o *GetBeaconParams) WithContext(ctx context.Context) *GetBeaconParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get beacon params
func (o *GetBeaconParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get beacon params
func (o *GetBeaconParams) WithHTTPClient(client *http.Client) *GetBeaconParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get beacon params
func (o *GetBeaconParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBeaconParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
