// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostProbeParams creates a new PostProbeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostProbeParams() *PostProbeParams {
	return &PostProbeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostProbeParamsWithTimeout creates a new PostProbeParams object
// with the ability to set a timeout on a request.
func NewPostProbeParamsWithTimeout(timeout time.Duration) *PostProbeParams {
	return &PostProbeParams{
		timeout: timeout,
	}
}

// NewPostProbeParamsWithContext creates a new PostProbeParams object
// with the ability to set a context for a request.
func NewPostProbeParamsWithContext(ctx context.Context) *PostProbeParams {
	return &PostProbeParams{
		Context: ctx,
	}
}

// NewPostProbeParamsWithHTTPClient creates a new PostProbeParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostProbeParamsWithHTTPClient(client *http.Client) *PostProbeParams {
	return &PostProbeParams{
		HTTPClient: client,
	}
}

/*
PostProbeParams contains all the parameters to send to the API endpoint

	for the post probe operation.

	Typically these are written to a http.Request.
*/
type PostProbeParams struct {

	/* Namespace.

	   the repo namespace the probe should check for image updates
	*/
	Namespace string

	/* Repo.

	   the repo name which the probe should check for image updates
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post probe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProbeParams) WithDefaults() *PostProbeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post probe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostProbeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post probe params
func (o *PostProbeParams) WithTimeout(timeout time.Duration) *PostProbeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post probe params
func (o *PostProbeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post probe params
func (o *PostProbeParams) WithContext(ctx context.Context) *PostProbeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post probe params
func (o *PostProbeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post probe params
func (o *PostProbeParams) WithHTTPClient(client *http.Client) *PostProbeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post probe params
func (o *PostProbeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the post probe params
func (o *PostProbeParams) WithNamespace(namespace string) *PostProbeParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the post probe params
func (o *PostProbeParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithRepo adds the repo to the post probe params
func (o *PostProbeParams) WithRepo(repo string) *PostProbeParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the post probe params
func (o *PostProbeParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *PostProbeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param namespace
	qrNamespace := o.Namespace
	qNamespace := qrNamespace
	if qNamespace != "" {

		if err := r.SetQueryParam("namespace", qNamespace); err != nil {
			return err
		}
	}

	// query param repo
	qrRepo := o.Repo
	qRepo := qrRepo
	if qRepo != "" {

		if err := r.SetQueryParam("repo", qRepo); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
