// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go

// Package oci is a generated GoMock package.
package oci

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// run mocks base method.
func (m *MockRunner) run(cmds ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range cmds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "run", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// run indicates an expected call of run.
func (mr *MockRunnerMockRecorder) run(cmds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "run", reflect.TypeOf((*MockRunner)(nil).run), cmds...)
}
