// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerBeaconDescribeResponse server beacon describe response
//
// swagger:model server.BeaconDescribeResponse
type ServerBeaconDescribeResponse struct {

	// probes
	Probes []string `json:"probes"`

	// registry
	Registry string `json:"registry,omitempty"`

	// runtime
	Runtime string `json:"runtime,omitempty"`
}

// Validate validates this server beacon describe response
func (m *ServerBeaconDescribeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this server beacon describe response based on context it is used
func (m *ServerBeaconDescribeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerBeaconDescribeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerBeaconDescribeResponse) UnmarshalBinary(b []byte) error {
	var res ServerBeaconDescribeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
